import json, re

HY = [
    {"chapter_id": 1, "chapter_title": "Why ENT?", "points": ["ENT covers ear, nose, throat, head & neck surgery", "Primary care sees 25% ENT complaints", "Unilateral symptoms = red flag until proven otherwise", "Referred pain is common: ear pain may be laryngeal cancer", "Never ignore progressive unilateral hearing loss"]},
    {"chapter_id": 3, "chapter_title": "Nasal Anatomy", "points": ["Nasal septum divides nasal cavity; deviation is common", "Turbinates humidify and filter air", "Olfactory nerve (CN I) enters through cribriform plate", "Paranasal sinuses drain into middle meatus (maxillary, frontal, anterior ethmoid)", "Posterior ethmoid and sphenoid drain into superior meatus"]},
    {"chapter_id": 4, "chapter_title": "Epistaxis", "points": ["90% anterior from Kiesselbach plexus (Little area)", "10% posterior - more dangerous, older patients, warfarin", "First aid: lean forward, pinch soft nose x10 min", "Silver nitrate cautery for anterior bleeds", "Posterior pack or endoscopic ligation for refractory cases", "Check BP and INR in recurrent epistaxis"]},
    {"chapter_id": 5, "chapter_title": "Rhinosinusitis", "points": ["Acute <4 weeks; chronic >12 weeks with symptoms", "Viral URTI = most common cause; antibiotics not needed first 10 days", "Amoxicillin-clavulanate if bacterial suspected", "CT scan for chronic or complicated cases", "Nasal polyps = chronic eosinophilic inflammation; respond to steroids", "FESS (functional endoscopic sinus surgery) for refractory cases"]},
    {"chapter_id": 6, "chapter_title": "Sinusitis Complications", "points": ["Orbital cellulitis most common complication (ethmoid)", "Chandler classification I-V (preseptal to cavernous sinus)", "Cavernous sinus thrombosis: bilateral proptosis, high fever, CN palsy", "Meningitis, brain abscess from frontal sinusitis (Pott puffy tumor)", "CT with contrast for orbital complications", "Surgical drainage for orbital abscess (Chandler III+)"]},
    {"chapter_id": 7, "chapter_title": "Ear Anatomy", "points": ["External ear: auricle + EAC (outer 1/3 cartilage, inner 2/3 bone)", "Tympanic membrane: pars tensa + pars flaccida (Shrapnell)", "Ossicles: malleus, incus, stapes - amplify sound 20x", "Cochlea: organ of Corti, hair cells, tonotopic map (base=high freq)", "Facial nerve exits stylomastoid foramen", "Eustachian tube: equalizes pressure, drains middle ear"]},
    {"chapter_id": 8, "chapter_title": "Ear Infections", "points": ["Otitis externa: Pseudomonas, treat with topical ciprofloxacin", "Malignant OE: diabetics, Pseudomonas, skull base invasion - IV antibiotics", "AOM: Strep pneumoniae, H.influenzae; amoxicillin first line", "Glue ear (OME): commonest cause of childhood hearing loss; grommets if persistent", "CSOM: chronic perforation with discharge; beware cholesteatoma", "Cholesteatoma: keratin debris, erodes bone, requires surgery"]},
    {"chapter_id": 9, "chapter_title": "Hearing Loss", "points": ["Conductive: problem in external/middle ear; Weber lateralizes to affected side", "Sensorineural: cochlea or nerve; Weber lateralizes to better ear", "Rinne positive (AC>BC) = normal or SNHL; Rinne negative (BC>AC) = CHL", "Sudden SNHL = emergency; IV steroids within 72 hours", "Presbycusis: bilateral high-frequency loss in elderly", "Noise-induced: 4kHz notch on audiogram"]},
    {"chapter_id": 10, "chapter_title": "Dizziness & Vertigo", "points": ["BPPV: commonest; posterior canal; Dix-Hallpike test; Epley maneuver curative", "Menieres: triad of episodic vertigo + unilateral hearing loss + tinnitus", "Vestibular neuritis: sudden severe vertigo, no hearing loss, post-viral", "HINTS exam differentiates central from peripheral vertigo", "Central vertigo red flags: direction-changing nystagmus, neurological signs", "Acoustic neuroma: unilateral SNHL + tinnitus; MRI for diagnosis"]},
    {"chapter_id": 11, "chapter_title": "Larynx Anatomy", "points": ["Supraglottis: epiglottis, false cords, arytenoids", "Glottis: true vocal cords (most common site for cancer)", "Subglottis: below cords to cricoid", "RLN innervates all intrinsic laryngeal muscles except cricothyroid (SLN)", "Left RLN loops under aortic arch - longer course, more vulnerable", "Cricothyroid membrane: emergency airway access site"]},
    {"chapter_id": 12, "chapter_title": "Voice Disorders", "points": ["Hoarseness >3 weeks = refer for laryngoscopy to exclude cancer", "Vocal nodules: bilateral, middle 1/3, in voice abusers; respond to therapy", "Polyps: unilateral, hemorrhagic; require surgical removal", "Reinkes edema: smokers; bilateral; voice low-pitched", "RLN palsy: unilateral = breathy voice; bilateral = stridor/airway emergency", "Laryngeal cancer: risk factors = smoking + alcohol; HPV in young patients"]},
    {"chapter_id": 13, "chapter_title": "Head & Neck Masses", "points": ["Rule of 80: 80% neck masses in adults are neoplastic, 80% of those are malignant", "Midline masses: thyroglossal cyst (moves with tongue), dermoid, thyroid", "Lateral neck: branchial cyst (2nd arch, anterior to SCM)", "Lymphadenopathy: >3 weeks, >1cm, hard, non-tender = red flag", "FNA (fine needle aspiration) first investigation for neck mass", "PET-CT for unknown primary with cervical metastasis"]},
    {"chapter_id": 14, "chapter_title": "Paediatric Airway", "points": ["Narrowest point in child larynx = subglottis (cricoid); in adult = glottis", "Croup (laryngotracheobronchitis): parainfluenza, barking cough, steeple sign", "Epiglottitis: H.influenzae, tripod position, thumb sign; do NOT examine throat", "Inhaled foreign body: sudden choking + unilateral wheeze; CXR in expiration", "Dexamethasone for croup; no steroids for epiglottitis (intubate first)", "Subglottic stenosis: commonest complication of prolonged intubation"]},
    {"chapter_id": 15, "chapter_title": "Tonsils & Adenoids", "points": ["Tonsillectomy indications: 7 episodes/year, 5 episodes x2 years, 3 episodes x3 years (Paradise criteria)", "Peritonsillar abscess: quinsy; uvula deviated away from abscess; drain + penicillin", "OSA in children: adenotonsillar hypertrophy commonest cause; adenotonsillectomy curative", "Post-tonsillectomy bleed: reactionary (within 24h) vs secondary (day 5-10)", "Return to theatre for primary post-tonsillectomy hemorrhage", "Adenoidectomy for OME + adenoid hypertrophy, recurrent AOM"]},
    {"chapter_id": 16, "chapter_title": "Foreign Bodies", "points": ["Button batteries = emergency; liquefaction necrosis within 2 hours", "Disc batteries in nose/ear/esophagus: remove immediately", "Esophageal FB: dysphagia, drooling; at cricopharyngeus (C6) most common", "Nasal FB: unilateral purulent discharge in a child until proven otherwise", "Airway FB: rigid bronchoscopy under GA; never blind finger sweep", "Fish bone in throat: soft tissue neck X-ray; flexible scope if normal"]},
    {"chapter_id": 17, "chapter_title": "When to Refer", "points": ["Urgent 2-week wait: unilateral neck mass, hoarseness >3 wk in smoker, unilateral epistaxis", "Sudden SNHL: same-day ENT referral", "Stridor in any age: emergency", "Orbital signs in sinusitis: immediate referral", "Persistent unilateral nasal symptoms: exclude malignancy", "Facial nerve palsy: urgent assessment; Ramsay Hunt if vesicles"]},
    {"chapter_id": 18, "chapter_title": "Clinical Pearls", "points": ["Referred otalgia pathways: CN V, IX, X - check throat, larynx, tonsil", "Trotter triad: unilateral hearing loss + palatal paralysis + trigeminal pain = nasopharyngeal cancer", "Gradenigo syndrome: otitis media + CN VI palsy + retroorbital pain", "Eagle syndrome: elongated styloid process causing throat pain", "Samter triad: asthma + aspirin sensitivity + nasal polyps", "Bezold abscess: mastoiditis tracking along sternomastoid"]},
    {"chapter_id": 19, "chapter_title": "ENT & Evolution", "points": ["Descended larynx in humans = speech but increases choking risk", "Eustachian tube more horizontal in children = higher AOM rate", "Sinus evolution unclear; may reduce skull weight or warm air", "Tonsils and adenoids = Waldeyer ring; immune surveillance", "Ear ossicles evolved from reptilian jaw bones", "Presbycusis = inevitable consequence of accumulated noise exposure"]},
    {"chapter_id": 20, "chapter_title": "Patient Counselling", "points": ["Informed consent: capacity, information, voluntariness", "Risk communication: absolute vs relative risk", "Tracheostomy counselling: temporary vs permanent, tube types, emergencies", "Hearing aid counselling: realistic expectations, acclimatization period", "Post-laryngectomy: voice rehabilitation options (TEP, electrolarynx, esophageal speech)", "Tinnitus: no cure but management (TRT, CBT, maskers)"]},
]

D = 'data.js'
c = open(D).read()

# Get existing chapter_ids in high_yield
import re
existing = set(int(x) for x in re.findall(r'"chapter_id":\s*(\d+)', c[c.index('"high_yield"'):]))
print("Existing:", existing)

new_entries = [h for h in HY if h["chapter_id"] not in existing]
print("Adding:", len(new_entries), "entries")

if new_entries:
    new_json = ', '.join(json.dumps(e, ensure_ascii=False) for e in new_entries)
    old = '"high_yield":['
    new = '"high_yield":[' + new_json + ', '
    c = c.replace(old, new, 1)
    open(D, 'w', encoding='utf-8').write(c)
    print("Done")
else:
    print("Nothing to add")
